version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flask_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "8000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/flask_app
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  postgres_data:
    driver: local
